# Adicione suas credenciais do Supabase abaixo
SUPABASE_URL = "https://wrhysptzozlodsgbonor.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyaHlzcHR6b3psb2RzZ2Jvbm9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjYwMzksImV4cCI6MjA2NDU0MjAzOX0.Clp7BvkTZDxnD3iXhFITBDdnnwJ-6-BYwtPVTi2OFmc" 